import { BookOpenText, CalendarDays, FileText, MoreHorizontal, Pencil, Pin, Plus, Search, Sparkles, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Note } from '../types';
import { EmptyState, ErrorState, Loading } from '../components/ui/Feedback';

interface NotesPageProps { notes: Note[]; loading: boolean; error: string; search: string; onSearch: (value: string) => void; onRetry: () => void; onCreate: () => void; onEdit: (note: Note) => void; onPin: (note: Note) => void; onDelete: (note: Note) => void }
const updatedLabel = (value: string) => { const date = new Date(value); const days = Math.floor((Date.now() - date.getTime()) / 86_400_000); if (days <= 0) return 'Updated today'; if (days === 1) return 'Updated yesterday'; if (days < 7) return `Updated ${days} days ago`; return `Updated ${new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(date)}`; };

export function NotesPage({ notes, loading, error, search, onSearch, onRetry, onCreate, onEdit, onPin, onDelete }: NotesPageProps) {
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const pinnedCount = notes.filter((note) => note.pinned).length;
  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">KEEP WHAT MATTERS</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-ink sm:text-[36px]">Notes<span className="text-amber-400">.</span></h1><p className="mt-2 text-sm text-slate-500">A home for the ideas you don’t want to lose.</p></div><span className="flex items-center gap-2 text-xs text-slate-500"><FileText size={15} />{notes.length} {notes.length === 1 ? 'note' : 'notes'}<span className="h-1 w-1 rounded-full bg-slate-300" />{pinnedCount} pinned</span></div>
    <div className="mt-7 flex flex-col gap-3 sm:flex-row"><div className="search-box flex-1"><Search size={17} className="shrink-0 text-slate-400" /><input aria-label="Search notes" value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search titles and notes…" /></div><button className="button-secondary justify-center" onClick={onCreate}><Plus size={16} /> Write a note</button></div>
    <div className="mt-6">{loading ? <Loading label="Gathering your notes" /> : error ? <ErrorState message={error} onRetry={onRetry} /> : notes.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{notes.map((note) => <article key={note.id} className={`note-card ${note.pinned ? 'note-card-pinned' : ''}`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate font-display text-base font-semibold text-slate-800">{note.title}</h2>{note.pinned && <Pin size={13} className="shrink-0 fill-amber-300 text-amber-500" aria-label="Pinned" />}</div><div className="relative"><button className="icon-button -mr-2 -mt-2" aria-label={`Options for ${note.title}`} aria-expanded={openMenu === note.id} onClick={() => setOpenMenu(openMenu === note.id ? null : note.id)}><MoreHorizontal size={18} /></button>{openMenu === note.id && <div className="action-menu action-menu-right"><button onClick={() => { setOpenMenu(null); onEdit(note); }}><Pencil size={14} /> Edit note</button><button onClick={() => { setOpenMenu(null); onPin(note); }}><Pin size={14} />{note.pinned ? 'Unpin note' : 'Pin note'}</button><button className="text-red-600" onClick={() => { setOpenMenu(null); onDelete(note); }}><Trash2 size={14} /> Delete note</button></div>}</div></div><button className="mt-3 block w-full text-left" onClick={() => onEdit(note)}><p className="note-content line-clamp-6 whitespace-pre-wrap">{note.content}</p></button><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-3"><span className="flex items-center gap-1.5 text-[11px] text-slate-400"><CalendarDays size={12} />{updatedLabel(note.updatedAt)}</span><div className="flex gap-1"><button className="note-action" aria-label={`Edit ${note.title}`} onClick={() => onEdit(note)}><Pencil size={14} /></button><button className="note-action" aria-label={note.pinned ? `Unpin ${note.title}` : `Pin ${note.title}`} onClick={() => onPin(note)}><Pin size={14} /></button><button className="note-action hover:text-red-500" aria-label={`Delete ${note.title}`} onClick={() => onDelete(note)}><Trash2 size={14} /></button></div></div></article>)}</div> : search ? <EmptyState icon={<Search size={22} />} title="No notes found" description={`Nothing matched “${search}”. Try a different search.`} action={<button className="text-link" onClick={() => onSearch('')}>Clear search</button>} /> : <EmptyState icon={<BookOpenText size={22} />} title="Your ideas have a place" description="Write down an idea, save a useful detail, or start a list for later." action={<button className="button-primary" onClick={onCreate}><Plus size={16} /> Write your first note</button>} />}</div>
    {!loading && !error && notes.length > 0 && <p className="mt-7 flex items-center justify-center gap-2 text-xs text-slate-400"><Sparkles size={14} /> Your pinned notes always stay close.</p>}
  </div>;
}