import { CalendarDays, Check, CheckCheck, CheckCircle2, Circle, Clock3, ListTodo, MoreHorizontal, Pencil, Plus, Search, SlidersHorizontal, Sparkles, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Todo } from '../types';
import type { TodoFilter, TodoSort } from '../services/todo.service';
import { EmptyState, ErrorState, Loading } from '../components/ui/Feedback';

interface TasksPageProps { todos: Todo[]; loading: boolean; error: string; search: string; filter: TodoFilter; sort: TodoSort; onSearch: (value: string) => void; onFilter: (value: TodoFilter) => void; onSort: (value: TodoSort) => void; onRetry: () => void; onCreate: () => void; onEdit: (todo: Todo) => void; onToggle: (todo: Todo) => void; onDelete: (todo: Todo) => void }

const tabs: { label: string; value: TodoFilter }[] = [{ label: 'All tasks', value: 'all' }, { label: 'In progress', value: 'active' }, { label: 'Completed', value: 'completed' }, { label: 'High priority', value: 'high' }];
const priorityClass: Record<string, string> = { LOW: 'badge-low', MEDIUM: 'badge-medium', HIGH: 'badge-high' };
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(value));

export function TasksPage({ todos, loading, error, search, filter, sort, onSearch, onFilter, onSort, onRetry, onCreate, onEdit, onToggle, onDelete }: TasksPageProps) {
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const pending = todos.filter((todo) => !todo.completed).length;
  const completed = todos.length - pending;
  const intro = filter === 'completed' ? 'Look at everything you’ve already done.' : filter === 'high' ? 'The important things, all in one place.' : 'Small steps add up. Pick one and begin.';

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">YOUR DAY, YOUR PACE</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-ink sm:text-[36px]">Tasks<span className="text-violet-400">.</span></h1><p className="mt-2 text-sm text-slate-500">{intro}</p></div><div className="flex items-center gap-4 text-xs text-slate-500"><span><strong className="text-slate-800">{pending}</strong> to do</span><span className="h-1 w-1 rounded-full bg-slate-300" /><span><strong className="text-slate-800">{completed}</strong> done</span></div></div>
    <div className="mt-7 flex flex-col gap-3 sm:flex-row"><div className="search-box flex-1"><Search size={17} className="shrink-0 text-slate-400" /><input aria-label="Search tasks" value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search your tasks…" /></div><label className="sort-box"><SlidersHorizontal size={15} className="text-slate-400" /><span className="sr-only">Sort tasks</span><select aria-label="Sort tasks" value={sort} onChange={(event) => onSort(event.target.value as TodoSort)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="priority">Priority</option><option value="dueDate">Due date</option></select></label></div>
    <div role="tablist" aria-label="Filter tasks" className="filter-tabs mt-5">{tabs.map((tab) => <button key={tab.value} role="tab" aria-selected={filter === tab.value} className={`filter-tab ${filter === tab.value ? 'filter-tab-active' : ''}`} onClick={() => onFilter(tab.value)}>{tab.label}<span className="tab-count">{tab.value === 'all' ? todos.length : tab.value === 'active' ? pending : tab.value === 'completed' ? completed : todos.filter((todo) => todo.priority === 'HIGH').length}</span></button>)}</div>
    <div className="mt-5">{loading ? <Loading label="Getting your tasks" /> : error ? <ErrorState message={error} onRetry={onRetry} /> : todos.length ? <div className="space-y-3">{todos.map((todo) => <article key={todo.id} className={`task-card ${todo.completed ? 'task-card-done' : ''}`}>
      <button className={`task-check ${todo.completed ? 'task-check-done' : ''}`} aria-label={todo.completed ? `Mark ${todo.title} as active` : `Complete ${todo.title}`} aria-pressed={todo.completed} onClick={() => onToggle(todo)}>{todo.completed && <Check size={15} strokeWidth={2.5} />}</button>
      <div className="min-w-0 flex-1"><h2 className={`truncate text-sm font-semibold ${todo.completed ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{todo.title}</h2>{todo.description && <p className={`mt-1.5 line-clamp-2 text-xs leading-5 ${todo.completed ? 'text-slate-400' : 'text-slate-500'}`}>{todo.description}</p>}<div className="mt-3 flex flex-wrap items-center gap-2"><span className={`priority-badge ${priorityClass[todo.priority]}`}><span className="priority-dot" />{todo.priority.charAt(0) + todo.priority.slice(1).toLowerCase()}</span>{todo.dueDate && <span className={`date-badge ${!todo.completed && new Date(todo.dueDate) < new Date(new Date().setHours(0, 0, 0, 0)) ? 'date-overdue' : ''}`}><CalendarDays size={12} />{formatDate(todo.dueDate)}</span>}</div></div>
      <div className="relative flex items-center gap-1"><button className="icon-button task-action" aria-label={`Edit ${todo.title}`} onClick={() => onEdit(todo)}><Pencil size={16} /></button><button className="icon-button task-action" aria-label={`Delete ${todo.title}`} onClick={() => onDelete(todo)}><Trash2 size={16} /></button><button className="icon-button task-menu-trigger" aria-label={`More options for ${todo.title}`} aria-expanded={openMenu === todo.id} onClick={() => setOpenMenu(openMenu === todo.id ? null : todo.id)}><MoreHorizontal size={18} /></button>{openMenu === todo.id && <div className="action-menu"><button onClick={() => { setOpenMenu(null); onEdit(todo); }}><Pencil size={14} /> Edit task</button><button onClick={() => { setOpenMenu(null); onToggle(todo); }}>{todo.completed ? <Circle size={14} /> : <Check size={14} />}{todo.completed ? 'Mark as active' : 'Mark complete'}</button><button className="text-red-600" onClick={() => { setOpenMenu(null); onDelete(todo); }}><Trash2 size={14} /> Delete task</button></div>}</div>
    </article>)}</div> : search ? <EmptyState icon={<Search size={22} />} title="No tasks found" description={`Nothing matched “${search}”. Try another search or clear the field.`} action={<button className="text-link" onClick={() => onSearch('')}>Clear search</button>} /> : <EmptyState icon={filter === 'completed' ? <CheckCheck size={22} /> : filter === 'high' ? <Sparkles size={22} /> : filter === 'active' ? <Clock3 size={22} /> : <ListTodo size={22} />} title={filter === 'completed' ? 'Nothing completed yet' : filter === 'high' ? 'No high-priority tasks' : filter === 'active' ? 'All caught up' : 'Your list starts here'} description={filter === 'completed' ? 'Complete a task and your progress will show up here.' : 'Add a task to gather your plans in one calm place.'} action={<button className="button-primary" onClick={onCreate}><Plus size={16} /> Create a task</button>} />}</div>
    {!loading && !error && todos.length > 0 && <div className="mt-6 flex items-center justify-center gap-2 text-xs text-slate-400"><CheckCircle2 size={15} /> You’re making progress, one task at a time.</div>}
  </div>;
}